$('#esconderDesenho').click(function(){
    $('#drax').hide();
})
$('#aparecerDesenho').click(function(){
    $('#drax').show();
});
$('#esconderSerie').click(function(){
    $('#groot').hide();
})
$('#aparecerSerie').click(function(){
    $('#groot').show();
});
$('#esconderFilmes').click(function(){
    $('#rocket').hide();
})
$('#aparecerFilmes').click(function(){
    $('#rocket').show();
});
$('#fundoPrimary').click(function(){
    $('body').addClass('bg-primary')
});
$('#fundoSecondary').click(function(){
    $('body').addClass('bg-secondary')
});
$('#fundoSucess').click(function(){
    $('body').addClass('bg-sucess')
});
$('#fundoDanger').click(function(){
    $('body').addClass('bg-danger')
});
$('#fundoWarning').click(function(){
    $('body').addClass('bg-warning')
});
$('#fundoInfo').click(function(){
    $('body').addClass('bg-info')
});
$('#fundoLight').click(function(){
    $('body').addClass('bg-light')
});
$('#fundoDark').click(function(){
    $('body').addClass('bg-dark')
});
$('#vanish').click(function(){
    $('body').removeClass('bg-dark bg-light bg-info bg-warning bg-danger bg-sucess bg-secondary bg-primary')
});
$('#enviar').click(function(){
    alert("Nome: " + $('#nome').val() + "\n E-Mail: " + $('#email').val() + "\n Mensagem: " + $('#mensagem').val());
});